// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgastilinsbulznfqtfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYXN0aWxpbnNidWx6bmZxdGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjYxODksImV4cCI6MjA1NzY0MjE4OX0.K90MUyQPQ6Ovk1vH5apiNUt0hq7h5y9xD5Da6v6MIlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);